# Generated by Django 2.2 on 2020-01-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
